### ISSUE TITLE
Bareword "E_NOT_BUSY" not allowed

### ISSUE THREAD

**Issue by eserte** [iph0/AnyEvent-RipeRedis-Cluster#1]
On one of my smoker systems I see the following test failure (0.24, 0.25_01):
```
Bareword "E_NOT_BUSY" not allowed while "strict subs" in use at t/01-error-codes.t line 33.
Execution of t/01-error-codes.t aborted due to compilation errors.
# Looks like your test exited with 255 before it could output anything.
t/01-error-codes.t ... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 26/26 subtests 
```

Maybe this happens if AnyEvent::RipeRedis is too old — in this case 0.36 is installed. 0.38 and later seems to be fine.

**Comment by iph0** [comment]
Thank you for your report. I fix that right now.

**Comment by iph0** [comment]
Done. Fixed in pre-release version. New release on CPAN will be in closest time. Thank you again.
